# ベースイメージ
FROM node:18-alpine

# 作業ディレクトリを設定
WORKDIR /app

# package.json と package-lock.json をコピー
COPY package*.json ./

# 依存パッケージのインストール
RUN npm install

# アプリのソースコードをコピー
COPY . .

# Reactアプリを起動
CMD ["npm", "start"]
